F05
chadi-shwada/crazee-burger pull request #8
Opened 2023-10-10 14:05 UTC by chadi-shwada

2023-10-10 15:06 UTC, KentuckySato requested changes
Extension de fichier à retiré dans les imports mais sinon RAS sur le code

2023-10-10 15:06 UTC, KentuckySato commented on src/components/pages/order/Main/Main.jsx
> +import Menu from "./Menu.jsx";
Extension de fichier détecté

2023-10-10 15:06 UTC, KentuckySato commented on src/components/pages/order/Main/Menu.jsx
> +import Card from "../../../reusable-ui/Card.jsx";
.jsx

2023-10-10 16:53 UTC, KentuckySato approved these changes
Approve !!! 👏🏼

2023-10-10 20:21 UTC, A-Fidele approved these changes

2023-10-10 20:21 UTC, A-Fidele commented on src/components/reusable-ui/Card.jsx
> +      font-family: "Amatic SC", cursive;
suggestion: ajouter la police dans le design system

2023-10-11 08:53 UTC, YohannMaiVan requested changes
Tout me parait bien, je vois juste niveau la width des boutons "ajouter" qui me paraît grande, peut être la modifier ? sinon tout est bon pour moi :)

2023-10-11 11:55 UTC, KentuckySato approved these changes

2023-10-11 11:55 UTC, KentuckySato commented on src/components/reusable-ui/Card.jsx
> +    <CardStyled className="produit">
```suggestion
    <CardStyled className="product">
```

2023-10-11 12:01 UTC, KentuckySato commented
Juste 1 suggestion mais c'est ok pour moi ✅

2023-10-11 12:28 UTC, merged